# Generated by Django 3.2.8 on 2021-10-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='values',
            new_name='value',
        ),
    ]
